# Practical_6: Numpy

Exercise 1:
Create a NumPy array of integers from 1 to 10.


In [7]:
import numpy as np
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
Exercise 2:
Create a 3x3 NumPy array filled with zeros.


In [12]:
b = np.array([[0,0,0],[0,0,0],[0,0,0]])
b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [13]:
c= np.zeros((3,3))
c

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.


In [17]:
d= np.linspace(0,5,10)
d

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [18]:
e = np.linspace(0,10,5)
e

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [21]:
m = np.linspace(10,30,10)
m

array([10.        , 12.22222222, 14.44444444, 16.66666667, 18.88888889,
       21.11111111, 23.33333333, 25.55555556, 27.77777778, 30.        ])

In [ ]:
Exercise4:
Create a 5x5 identity matrix using NumPy.

In [23]:
F= np.eye(5)
F

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

In [35]:
M= np.random.randint(0,2,size=(4,4))
M

array([[1, 1, 1, 0],
       [0, 0, 1, 1],
       [0, 1, 1, 0],
       [0, 1, 0, 0]])

In [ ]:
Exercise 6:
Find the shape of a NumPy array.


In [39]:
x = np.array([1,2,3])
print(x.shape)


(3,)


In [ ]:
Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

In [104]:
n= np.arange(16).reshape(4,4)
n

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [105]:
subm = n[0:2, 0:3]
print(subm)

[[0 1 2]
 [4 5 6]]


In [ ]:
Exercise 8:

Find the data type of the elements in a NumPy array.

In [9]:
a = np.array([4,46,7])
print(a.dtype)
c= np.array([4.2,6.7])
print(c.dtype)
d=np.

int64
float64


In [ ]:
Exercise 9:

Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

In [17]:
n=np.arange(1,101)
even= n[(n%2==0)]
print(even)


[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [18]:
odd= n[(n%2!=0)]
print(odd)


[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


Exercise 10:

Gemnerate a 6x6 matrix of random integers between 10 and 50.

In [20]:
x=np.random.randint(10,51,size=(6,6))
x

array([[26, 11, 17, 22, 12, 34],
       [37, 28, 28, 17, 10, 29],
       [11, 42, 17, 36, 25, 34],
       [27, 28, 23, 46, 27, 35],
       [40, 32, 23, 12, 43, 45],
       [12, 33, 37, 37, 50, 42]])

Exercise 11:

Slice a 2D NumPy array to extract a submatrix.

In [24]:
y=np.random.randint(10,size=(3,5))
y[1,]
y[0]
y[2]

array([0, 5, 1, 6, 1])

In [93]:
y=np.random.randint(10,size=(3,5))
y

array([[0, 4, 6, 8, 2],
       [1, 7, 1, 1, 9],
       [9, 0, 7, 1, 0]])

In [103]:
y=np.random.randint(10,size=(3,5))
subm = y[0:2, 0:3]
print(subm)

[[4 8 2]
 [9 7 7]]


In [ ]:
Exercise 12:

Calculate the sum of all elements in a NumPy array.

In [26]:
a=np.sum([3,5,6,7,8])
a

29

Exercise 13:

Calculate the mean, median, and standard deviation of a NumPy array.

In [27]:
b=np.mean([4,5,6,7,5,8,9])
b


6.285714285714286

In [29]:
c=np.median([4,5,6,7,5,8,9])
c

6.0

In [30]:
c=np.std([4,5,6,7,5,8,9])
c

1.665986255670086

Exercise 14:

Find the maximum and minimum values in a NumPy array.b

In [32]:
y=np.max([10,40,30,32])
y

40

In [33]:
y=np.min([10,40,32])
y

10

Exercise 15:

Create a NumPy array of 20 random integers and find the index of the maximum value.b

In [38]:
b= np.random.randint(1,20,size=(4,4))
np.argmax(b)

1

Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.


In [160]:
b= np.arange(1,10).reshape(3,3)
print(b*b)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [149]:
b*b

array([0.00066029, 0.06324254, 0.17224907, 0.64168187, 0.01501337,
       0.00644436, 0.10259715, 0.31473121, 0.52684207, 0.05094398])

In [44]:
c= np.random.randint(1,10,size=(3,3))
c

array([[5, 8, 5],
       [8, 3, 8],
       [9, 6, 4]])

In [45]:
b*c

array([[ 30, 136,  10],
       [ 80,  48, 128],
       [ 45,  90,  36]])

Exercise 18:
Create a diagonal matrix from a given 1D array.


In [57]:
m = np.array([5,6,7,8])
np.diag(m)

array([[5, 0, 0, 0],
       [0, 6, 0, 0],
       [0, 0, 7, 0],
       [0, 0, 0, 8]])

In [59]:
x=np.array([9,10,7,8])
x
np.diag(x)

array([[ 9,  0,  0,  0],
       [ 0, 10,  0,  0],
       [ 0,  0,  7,  0],
       [ 0,  0,  0,  8]])

In [ ]:
Exercise 19:

Perform matrix multiplication on two 2D NumPy arrays.

In [168]:
M= np.arange(1,5).reshape(2,2)
M

array([[1, 2],
       [3, 4]])

In [170]:
N= np.arange(6,10).reshape(2,2)
N

array([[6, 7],
       [8, 9]])

In [171]:
N*M

array([[ 6, 14],
       [24, 36]])

In [64]:
N+M

array([[ 4,  9, 23],
       [15, 19, 14],
       [ 7, 20, 19]])

Exercise 20:

Flatten a 2D NumPy array into a 1D array.

In [174]:
M= np.arange(1,5).reshape(2,2)
M
m=np.concatenate(M)
print('2 D matrix : \n ', M) 
print('1 D matrix : \n ', m)



2 D matrix : 
  [[1 2]
 [3 4]]
1 D matrix : 
  [1 2 3 4]


In [ ]:
m=np.array

Exercise 21:

Stack two NumPy arrays vertically.

In [177]:
Y= np.arange(1,10).reshape(3,3)
Y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [178]:
X= np.arange(11,20).reshape(3,3)
X

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [183]:
M= np.vstack((X,Y))
M

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [ ]:
Exercise 22:

Stack two NumPy arrays horizontally.

In [184]:
X= np.arange(11,20).reshape(3,3)
X

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [185]:
Y= np.arange(1,10).reshape(3,3)
Y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [186]:
M= np.hstack((Y,X))
M

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [ ]:
Exercise 23:

Split a NumPy array into multiple sub-arrays.

In [116]:
m = np.array([1,2,3,4,5,6,7,8])
de = np.split(m,[1,3,2,5])
print(de)

[array([1]), array([2, 3]), array([], dtype=int64), array([3, 4, 5]), array([6, 7, 8])]


In [ ]:
Exercise 24:

Generate a random NumPy array and round each element to two decimal places.



In [190]:
b =np.random.random(30) 
np.around(b,decimals=2)

array([0.46, 0.22, 0.92, 0.03, 0.95, 0.38, 0.08, 0.84, 0.26, 0.31, 0.4 ,
       0.04, 0.51, 0.83, 0.06, 0.82, 0.49, 0.97, 0.61, 0.65, 0.6 , 0.81,
       0.32, 0.61, 0.35, 0.77, 0.83, 0.11, 0.45, 0.83])

In [ ]:
Exercise 25:

Find the unique elements of a NumPy array.

In [134]:
c= np.array([2,4,5,2,4,5,6,7,4,5,2])
np.unique(c)

array([2, 4, 5, 6, 7])

Exercise 26:

Replace all elements in a NumPy array that are less than a specific value with that value.

In [148]:
x=np.array([5,7,8,4,9,3])
value=8
for i in range(len(x)):
    if x[i]<8:
        x[i]=8
print(x)

[8 8 8 8 9 8]


---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.

```python
# Exercise 1
```

---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.

```python
# Exercise 2
```

---
9
### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

```python
# Exercise 3
```

---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.

```python
# Exercise 4
```

---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

```python
# Exercise 5
```

---

### Exercise 6:
Find the shape of a NumPy array.

```python
# Exercise 6
```

---

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

```python
# Exercise 7
```

---

### Exercise 8:
Find the data type of the elements in a NumPy array.

```python
# Exercise 8
```

---

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

```python
# Exercise 9
```

---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

```python
# Exercise 10
```

---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

```python
# Exercise 11
```

---

### Exercise 12:
Calculate the sum of all elements in a NumPy array.

```python
# Exercise 12
```

---

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

```python
# Exercise 13
```

---

### Exercise 14:
Find the maximum and minimum values in a NumPy array.

```python
# Exercise 14
```

---

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

```python
# Exercise 15
```

---

### Exercise 16:
Create a NumPy array and reverse its elements.

```python
# Exercise 16
```

---

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

```python
# Exercise 17
```

---

### Exercise 18:
Create a diagonal matrix from a given 1D array.

```python
# Exercise 18
```

---

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

```python
# Exercise 19
```

---

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

```python
# Exercise 20
```

---

### Exercise 21:
Stack two NumPy arrays vertically.

```python
# Exercise 21
```

---

### Exercise 22:
Stack two NumPy arrays horizontally.

```python
# Exercise 22
```

---

### Exercise 23:
Split a NumPy array into multiple sub-arrays.

```python
# Exercise 23
```

---

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

```python
# Exercise 24
```

---

### Exercise 25:
Find the unique elements of a NumPy array.

```python
# Exercise 25
```

---

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

```python
# Exercise 26
```

---

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

```python
# Exercise 27
```

---

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

```python
# Exercise 28
```

---

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

```python
# Exercise 29
```

---

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

```python
# Exercise 30
```

---

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).

```python
# Exercise 31
```

---

### Exercise 32:
Create two NumPy arrays and find the dot product.

```python
# Exercise 32
```

---

### Exercise 33:
Find the trace of a square NumPy matrix.

```python
# Exercise 33
```

---

### Exercise 34:
Create a 2D array and swap two rows.

```python
# Exercise 34
```

---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.

```python
# Exercise 35
```

---

### Exercise 36:
Find the determinant of a 3x3 matrix.

```python
# Exercise 36
```

---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

```python
# Exercise 37
```

---

### Exercise 38:
Solve a system of linear equations using NumPy.

```python
# Exercise 38
```

---

### Exercise 39:
Add Gaussian noise to a NumPy array.

```python
# Exercise 39
```

---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

```python
# Exercise 40
```

---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.

```python
# Exercise 41
```

---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.

```python
# Exercise 42
```

---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.

```python
# Exercise 43
```

---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.

```python
# Exercise 44
```

---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.

```python
# Exercise 45
```

---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.

```python
# Exercise 46
```

---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.

```python
# Exercise 47
```

---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.

```python
# Exercise 48
```

---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.

```python
# Exercise 49
```

---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.

```python
# Exercise 50
```

---

### Exercise 51:
Convert a NumPy array of radians to degrees.

```python
# Exercise 51
```

---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.

```python
# Exercise 52
```

---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.

```python
# Exercise 53
```

---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.

```python
# Exercise 54
```

---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).

```python
# Exercise 55
```

---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.

```python
# Exercise 56
```

---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.

```python
# Exercise 57
```

---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.

```python
# Exercise 58
```

---

### Exercise 59:
Compute the Frobenius norm of a matrix.

```python
# Exercise 59
```

---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.

```python
# Exercise 60
```

---
